version: '3'

services:
  web:
    restart: always
    image: kermanjt/kerman_jt
    env_file: .env
    volumes:
      - ./whooshee:/app/whooshee
      - ./static:/app/static
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    restart: always
    image: mysql:5.7
    env_file: .env
    volumes:
      - ./mysql/data/:/var/lib/mysql/
    ports:
      - '3306:3306'  #host物理直接映射端口为3306

  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/letsencrypt:/etc/letsencrypt:rw
      - ./nginx/log:/var/log/nginx
      - ./static:/opt/static
    ports:
      - "80:80"
      - "443:443"


